# Config file for Sights Lite

[drive]
enabled = false

    [drive.connection]
    port = "/dev/ttyS0"
    baudrate = 9600

    [drive.channels]
    left = 0
    right = 1

[arm]
enabled = false

    [arm.servos.SHOULDER]
    index = 15
    range_min = 900
    range_max = 2150
    home = 180
    presets = { drive = 147.6, dext = 76 }

    [arm.servos.ELBOW]
    index = 14
    range_min = 900
    range_max = 2340
    home = 0
    presets = { drive = 77.4, dext = 52 }

    [arm.servos.WRISTUD]
    index = 11
    range_min = 550
    range_max = 2370
    home = 80
    presets = { drive = 180, dext = 4 }

    [arm.servos.WRISTLR]
    index = 10
    range_min = 350
    range_max = 2450
    home = 90
    presets = { drive = 138.8, dext = 82 }

    [arm.servos.CLAW]
    index = 9
    range_min = 500
    range_max = 2450
    home = 0
    presets = { drive = 0, dext = 20 }

[camera]
width = 640
height = 480
framerate = 30
quality = 80

    [camera.devices]
    front = 0
    back = 4
    ir = 2

[sensors]
    [sensors.system_info]
    type = "system_info"
    enabled = true

    [sensors.temperature]
    type = "mlx90614"
    enabled = false

    [sensors.random]
    type = "random"
    enabled = true
    minimum = 10
    maximum = 20

    [sensors.gas]
    type = "sgp30"
    enabled = true
    mock = true

    [sensors.thermal_camera]
    type = "mlx90640"
    enabled = true
    interpolate = false
    mock = true
